//WEATHER PARAMETERS
#define WUNDERGROUND_API "<WUNDERGROUD_API>"
#define WUNDERGROUND_COUNTRY "<COUNTRY>"
#define WUNDERGROUND_CITY "<CITY>"

//GPS COORDINATES
const char* LAT = "<LATITUDE>";
const char* LNG = "<LONGITUDE>";

//DEFAULT SUNSET & SUNRISE HOURS
const int SUNSET_HOURS = 17;
const int SUNRISE_HOURS = 7;

//NTP CLIENT PARAMETERS
const char* NTP_POOL = "pool.ntp.org";


